### ISSUE TITLE
 make install.bat for legacy bios laptops

### ISSUE THREAD

**Issue by karungupta762** [corpnewt/gibMacOS#95] opened 2020-04-27 09:47 UTC
please update the make install. bat file

i am an old laptop user
hp 630 bios legacy

the usb pen drive blinks with dash when try to boot with open core and recovery  hd pkg install 

i3  m2370 cpu @2.40 ghz 2 cores 4 logical processor

chipset name clarkdale/arrandale

please update the make install.bat file to install open core 0.5.8 release/debug.zip as it has legacy support just like  open core  has the option to install any revision of clover like r5092 or r5114 ..please make a criteria for installing any version of open core depending upon the configuration of laptop/pc 

2020-04-26
@williambj1 williambj1 released this yesterday · 2 commits to 10f7ab8f7cb787d760534b9cce746356ebdeb07e since this release

Changes
OpenCorePkg
BootInstall: New version
Docs: Update Samples
Build: Added Ps2KeyboardDxe driver for DuetPkg
OcConsoleLib: Fixed handling 24-bit screen resolutions
Utilities: Move Duet tools to DuetPkg repository
EfiPkg
LegacyBios: Initial version

**Comment by corpnewt** [comment] 2020-05-08 09:13
Closed as duplicate of issue 94

**Closed by corpnewt** 2020-05-08 09:13 UTC
