### ISSUE TITLE
No internet connection in recovery mode

### ISSUE THREAD

**Issue by Emanuele-1998** [corpnewt/gibMacOS#47] opened 2019-11-25 23:22 UTC
I try install with high Sierra and clover  5092 but doesn’t work. I start the installer macOS with Ethernet but doesn’t download

I make the usb with makeinstall and I insert in the string (number of usb and r5092)

**Comment by corpnewt** [comment] 2019-11-26 11:41
Then the issue is beyond the scope of this script - and the script itself is not what is failing (as it is able to create your install, and you get to the installer). I'm closing this for that reason. 

-CorpNewt

**Closed by corpnewt** 2019-11-26 11:41 UTC

**Comment by Emanuele-1998** [comment] 2019-11-26 12:04
yes but it provides no connection even with the previous version and I don't know how to solve

I tested with 5092 version of clover

**Comment by deadair3210** [comment] 2019-11-26 15:55
The script only builds the recovery drive using the files from the downloaded files, if you need anything extra it has to be done manually from what I see

**Comment by Emanuele-1998** [comment] 2019-11-26 16:07
> The script only builds the recovery drive using the files from the downloaded files, if you need anything extra it has to be done manually from what I see

no I do not say something more but how to do it when you check no intener connection I tried also with the old version of clover 5092 but it does not go. I'm talking about making usb from windows

**Comment by deadair3210** [comment] 2019-11-26 16:17
You need drivers for macos to work with your hardware. Nothing to do with the script

**Comment by Emanuele-1998** [comment] 2019-11-26 17:14
> You need drivers for macos to work with your hardware. Nothing to do with the script

I have the drivers for my hardware. The script has to do with. 

https://github.com/corpnewt/gibMacOS/issues/42

**Comment by corpnewt** [comment] 2019-11-26 17:28
@deadair3210 is correct - MakeInstall just creates the internet install USB, then copies the default Clover EFI to the first partition, and dds the boot0 and boot1 files to the MBR and PBR respectively.

Your connection trouble is not an issue with the script as it has created the internet install USB for you, and your screenshot shows that it boots.  As I explained in your other issue, this is likely an issue with Clover (or possibly your Clover configuration), and thus is not the fault of - and outside - the scope of my script.

If you need help setting up Clover - you'll likely want to work with a forum or discord server that provides support.  The issues threads for the script are not the proper place for general support.

-CorpNewt
