### ISSUE TITLE
DiskPart exited with non-zero status (2147755026).  Aborting.

### ISSUE THREAD

**Issue by Lolisemo** [corpnewt/gibMacOS#22] opened 2019-09-26 03:39 UTC
I want to make install for flash drive, but i have an error:
Using MBR...

Microsoft DiskPart, ўҐабЁп 10.0.17763.1

(C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).
Ќ  Є®¬ЇмовҐаҐ: DESKTOP-UKKPN4R

‚лЎа ­ ¤ЁбЄ 4.

ЋиЁЎЄ  б«г¦Ўл ўЁавг «м­ле ¤ЁбЄ®ў:
ЌҐв ­®бЁвҐ«п ў гбва®©бвўҐ.

DiskPart exited with non-zero status (2147755026).  Aborting.

**Comment by corpnewt** [comment] 2019-09-30 20:02
Typically this is caused by one of the following:

* Outdated, or incorrect Windows install
* Faulty USB drive

You can try updating Windows, using another USB drive, and running the script on another machine and see if that helps.

As the issue isn't with the script itself, I'll close this issue.

-CorpNewt

**Closed by corpnewt** 2019-09-30 20:02 UTC
