### ISSUE TITLE
No partition located on disk!

### ISSUE THREAD

**Issue by dobitamas** [corpnewt/gibMacOS#23] opened 2019-09-30 13:49 UTC
Gathering info...
 - Got CloverISO-5092.tar.lzma
Downloading...
Downloaded 2.51 MB of 2.51 MB (100.00%)
Extracting CloverISO-5092.tar.lzma...
Extracting CloverISO-5092.tar...
Extracting EFI from Clover-v2.5k-5092-X64.iso...
Extracting boot0af from Clover-v2.5k-5092-X64.iso...
Extracting boot1f32alt from Clover-v2.5k-5092-X64.iso...
Extracting boot6 from Clover-v2.5k-5092-X64.iso...
No partitions located on disk!

Press [enter] to return...

**Comment by corpnewt** [comment] 2019-09-30 20:04
Often caused by one of the following:

* Outdated or incorrectly setup Windows install
* 3rd party partition managers

The commands run by diskwin.py to map the disks and partitions are as follows:
```
wmic diskdrive get deviceid,model,index,size,partitions /format:csv
wmic path Win32_LogicalDiskToPartition get antecedent,dependent
wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype /format:csv
```
You can try running them individually and sending the results to verify what the script can see.

-CorpNewt

**Comment by TobiMiller** [comment] 2019-10-03 10:17
Hey,

same from my side.

But i had to set the "Show all devices"-flag to True to see my USB Stick. The problem is, that it is not marked as "removable" usb device. it is recognized as harddisk. "Sandisk USB Extreme".
i don't have any partition tool installed that i know of. Do you have an example?
Here are my logs from wmic before and after running your tool:

###############

`
wmic diskdrive get deviceid,model,index,size,partitions /format:csv
`

**BEFORE**

`Node,DeviceID,Index,Model,Partitions,Size
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE2,2,SanDisk Extreme USB Device,1,15685608960
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE0,0,Crucial_CT240M500SSD1,2,240054796800
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE1,1,SAMSUNG HD103SJ,2,1000202273280`

**AFTER**

`
Node,DeviceID,Index,Model,Partitions,Size
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE2,2,SanDisk Extreme USB Device,2,15685608960
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE0,0,Crucial_CT240M500SSD1,2,240054796800
DESKTOP-VN77TBO,\\.\PHYSICALDRIVE1,1,SAMSUNG HD103SJ,2,1000202273280`

###############

`
wmic path Win32_LogicalDiskToPartition get antecedent,dependent
`

**BEFORE**

`\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #0"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="C:"
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #0"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="D:"
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #1"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="E:"
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #2, Partition #0"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="H:"`

**AFTER**

`                   
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #0, Partition #0"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="C:"
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #0"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="D:"
\\DESKTOP-VN77TBO\root\cimv2:Win32_DiskPartition.DeviceID="Disk #1, Partition #1"  \\DESKTOP-VN77TBO\root\cimv2:Win32_LogicalDisk.DeviceID="E:"`

###############

`
wmic logicaldisk get deviceid,filesystem,volumename,size,drivetype /format:csv
`

**BEFORE**

`Node,DeviceID,DriveType,FileSystem,Size,VolumeName
DESKTOP-VN77TBO,C:,3,NTFS,239142219776,
DESKTOP-VN77TBO,D:,3,NTFS,508190257152,Dronefence
DESKTOP-VN77TBO,E:,3,NTFS,492008632320,Daten
DESKTOP-VN77TBO,F:,5,,,
DESKTOP-VN77TBO,G:,5,,,
DESKTOP-VN77TBO,H:,3,FAT32,15658385408,VOLUME`

**AFTER**

`
Node,DeviceID,DriveType,FileSystem,Size,VolumeName
DESKTOP-VN77TBO,C:,3,NTFS,239142219776,
DESKTOP-VN77TBO,D:,3,NTFS,508190257152,Dronefence
DESKTOP-VN77TBO,E:,3,NTFS,492008632320,Daten
DESKTOP-VN77TBO,F:,5,,,
DESKTOP-VN77TBO,G:,5,,,`

**Comment by dobitamas** [comment] 2019-10-03 23:36
I could maje the installer from linux. Fairly easy but a bit more typing

**Comment by corpnewt** [comment] 2019-10-04 00:20
@TobiMiller You can see that in the second and third commands, the volume attached at `H:` has disappeared entirely which is why it doesn't find any partitions on the disk - I'm not sure why though.  Regarding a third party partition manager - something like Paragon Hard Disk Manager may interefere.

@dobitamas Linux is far more competent than Windows (diskpart + wmic specifically) for disk management - so that would certainly be a more direct path.  I'm not sure what the issue is specifically, but most cases where something doesn't work right with MakeInstall, the problems are fixed by trying another USB drive, updating Windows, or trying on another machine.  I've even seen an instance where the system language interfered.

*Thanks Windows.*

If you happen to isolate the issue, and it's something I can check for/work around in the script, I'll add support - but it seems to be a rather inconsistent thing that only affects some users and the cause is difficult for me to pinpoint as I don't have the issue on any of my machines.

-CorpNewt

**Comment by TobiMiller** [comment] 2019-10-07 08:01
fine. got it working. but just the recovery. and the recovery doesnt work for me because of "server not reachable" problem. 
Is it possible to setup a full installer with your tool? I have downloaded the full system with 5-6GB but when i create the Stick it tries to install via web recovery ...

in the end I have created a stick with my old macbook. now my ryzentosh is running.

**Comment by corpnewt** [comment] 2019-10-07 10:39
It only creates an internet recovery USB - to create a full installer requires read/write HFS+ access in Windows.

Likely the "server not reachable" issue is due to the latest Clover update. Seems some network kexts aren't being injected.

**Comment by TobiMiller** [comment] 2019-10-07 11:36
@corpnewt 
oh ok. i had a misunderstanding what the tool is doing. so it can download the full files but can just create an online installer. why is there the "recovery installer"-toggle?

the clover bug should be mentioned till it is present on the wiki or in this repo.

thanks and best wishes.

**Comment by corpnewt** [comment] 2019-10-07 14:47
The gibMacOS script works on macOS, Windows, and Linux - macOS and Linux can read/write HFS+, and can therefore create a full install if need be (however this repo offers no companion installer creator scripts for those OSes). The MakeInstall script is for Windows *only* - so it only creates an internet installer as Windows cannot read/write HFS+.

The Clover bug is beyond the scope of this script and not something I intend to monitor and report on in this repo.

**Comment by corpnewt** [comment] 2019-10-07 16:50
As one of the two users here has gotten their issue resolved, and the other hasn't responded in a few days I'm going to close this issue.  If your issue persists, or you have more info to add @dobitamas, feel free to respond and I'll reopen it.

-CorpNewt

**Closed by corpnewt** 2019-10-07 16:50 UTC

**Comment by dobitamas** [comment] 2019-10-07 18:03
Sorry as I said I made a workaround and made the installer with ubuntu!
Thanks and keep up the good work!

**Comment by DaneE43** [comment] 2021-07-08 23:31
I am attempting to use gibmacos through windows 10, but the createinstall.bat and createinstall.py both won't let me use a partition.
![Screenshot 2021-07-08 163023](https://user-images.githubusercontent.com/83384667/125002478-e23e6700-e009-11eb-8a0d-043e16656dd9.jpg)
![Screenshot 2021-07-08 163042](https://user-images.githubusercontent.com/83384667/125002481-e36f9400-e009-11eb-97ce-f7987b909fce.jpg)
